browser = 'chrome'
url = 'https://ncplusgo.pl/'
title = 'nc+ GO'
timeout = '3s'
login = 'jakub.kucharski@ncplus.pl'
pas = '123buraczki'
zaloguj = '//*[@id="top"]/div/div/div/div/nav/ul/li[2]/a'
terazwtv = '//*[@id="top"]/div/div/div/div/div/nav/a[2]'
email = '//*[@id="Email"]'
password = '//*[@id="Password"]'
loginbutton = '//*[@id="login-form"]/fieldset/div/div[1]/div[3]/button'
rozumiem = '//*[@id="Home_Index"]/div[2]/div/div/div/a[2]'
terazwtvelement = '//*[@id="player-container"]/h1'
search = '//*[@id="top"]/div/div/div/div/nav/ul/li[1]/a/img'
inputsearch = '//*[@id="search"]'
kruk = 'kruk'
krukelement = '//*[@id="Search_Search"]/main/div/div[2]/ul/li[17]/div/div[3]/h2/a'
